# Generated by Django 4.1 on 2022-08-15 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_remove_planta_foto_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='data_chegada',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
