# Generated by Django 4.1 on 2022-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_alter_planta_data_chegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='foto_planta',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
