# Generated by Django 4.1 on 2022-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_planta_foto_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
