# Generated by Django 4.1 on 2022-08-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_alter_planta_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='nome_popular',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
