# Generated by Django 4.1 on 2022-08-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0006_alter_planta_nome_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='origem',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
