# Generated by Django 4.1 on 2022-08-15 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adubacao',
            name='data_adubacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='controle_de_pragas',
            name='data_controle',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='troca_de_vaso',
            name='data_troca',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
